site_name: ArgData
site_description: F1GP Data Library
site_favicon: favicon.ico
copyright: Copyright &copy; 2014-2017 Fredrik Meyer
repo_url: https://github.com/codemeyer/ArgData
theme: yeti
extra_css:
- css/argdata.css
pages:
- Home: index.md
- Guides:
  - Overview: overview.md
  - Quick Start: quick-start.md
  - Decompressed EXEs: decompressed-exe.md
- API:
  - Reference: api/reference.md
  - Palette Colors: api/palette-colors.md
#RemovePagesBlock
